<?php

/**
 * @file
 * Contains global functions for testing updates to a .module file.
 */

/**
 * Page controller that says hello.
 *
 * @return array
 *   A renderable array of the page content.
 */
function updated_module_hello(): array {
  return [
    '#markup' => 'Hello!',
  ];
}

/**
 * A test function to test if global functions are reloaded during an update.
 *
 * @return string
 */
function _updated_module_global1(): string {
  return "post-update-value";
}

/**
 * A test function to test if a new global function will be available after an update.
 */
function _updated_module_global2(): void {
}
