automatic_updates.settings:
  type: config_object
  label: 'Automatic Updates settings'
  mapping:
    cron:
      type: string
      label: 'Enable automatic updates during cron'
    cron_port:
      type: integer
      label: 'Port to use for finalization sub-request'
    allow_core_minor_updates:
      type: boolean
      label: 'Allow minor level Drupal core updates'
