automatic_updates.settings:
  type: config_object
  label: 'Automatic updates settings'
  mapping:
    psa_endpoint:
      type: string
      label: 'Endpoint URI for PSAs'
    enable_psa:
      type: boolean
      label: 'Enable PSA notices'
