automatic_updates.settings:
  type: config_object
  label: 'Automatic updates settings'
  mapping:
    psa_endpoint:
      type: string
      label: 'Endpoint URI for PSAs'
    enable_psa:
      type: boolean
      label: 'Enable PSA notices'
    notify:
      type: boolean
      label: 'Notify when PSAs are available'
    check_frequency:
      type: integer
      label: 'Frequency to check for PSAs, defaults to 12 hours'
    enable_readiness_checks:
      type: boolean
      label: 'Enable readiness checks'
    hashes_uri:
      type: string
      label: 'Endpoint URI for file hashes'
    ignored_paths:
      type: string
      label: 'List of files paths to ignore when running readiness checks'
    download_uri:
      type: string
      label: 'URI for downloading in-place update assets'
    enable_cron_updates:
      type: boolean
      label: 'Enable automatic updates via cron'
    enable_cron_security_updates:
      type: boolean
      label: 'Enable automatic updates for security releases via cron'
    database_update_handling:
      type: sequence
      label: 'Database update handling'
      sequence:
        type: string
        label: 'Tagged service to handle database updates'
